# Generated by Django 5.1.4 on 2024-12-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("rating", models.FloatField()),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Hospital",
                "verbose_name_plural": "Hospitals",
            },
        ),
        migrations.CreateModel(
            name="EmergencyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_summary", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("report_time", models.DateTimeField(auto_now_add=True)),
                (
                    "recommended_hospitals",
                    models.ManyToManyField(
                        related_name="emergency_reports", to="recommendations.hospital"
                    ),
                ),
            ],
        ),
    ]
